### ISSUE TITLE
Question about in-memory store choice

### ISSUE THREAD

**Issue by akolybelnikov** [chenyahui/gin-cache#22]
What was behind the decision in favour of `jellydator/ttlcache` over other libraries with high concurrency and unlimited capacity such as `go-cache` or `bigcache` for the in-memory store?

Also, are you planning to move to `ttlcache` v3?

**Comment by chenyahui** [comment]
1. The DeleteExpired  function of go-cache will block read and write util clean finished, it will iterate over all the elements because the expiration times of the elements are out of order. Go-cache will perform poorly when there are many elements.  https://github.com/patrickmn/go-cache/blob/master/cache.go#L931
2. bigcache is good enough. Because of the design principle of big-cache, a serialization and deserialization of objects are inevitably required when writing and reading. I want to omit this overhead. But bigcache does perform well with very large amounts of data.

Gin-cache can easily customize the cache store, you can choose according to your own ideas. https://github.com/chenyahui/gin-cache/blob/main/persist/cache.go#L12

**Comment by chenyahui** [comment]
I haven't read the code of ttlcache v3 carefully, and I don't know much about the improvements and features in it. Maybe I will access it after I study it.

**Comment by akolybelnikov** [comment]
Thank you for the answer.
